# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downanime.ui',
# licensing of 'downanime.ui' applies.
#
# Created: Thu Aug 29 18:36:22 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 474)
        self.central = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central.sizePolicy().hasHeightForWidth())
        self.central.setSizePolicy(sizePolicy)
        self.central.setStyleSheet("background-color: blue;")
        self.central.setObjectName("central")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.area_pesuisa = QtWidgets.QHBoxLayout()
        self.area_pesuisa.setObjectName("area_pesuisa")
        self.barra_pesquisa = QtWidgets.QTextEdit(self.central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barra_pesquisa.sizePolicy().hasHeightForWidth())
        self.barra_pesquisa.setSizePolicy(sizePolicy)
        self.barra_pesquisa.setMinimumSize(QtCore.QSize(0, 40))
        self.barra_pesquisa.setStyleSheet("background-color: white;")
        self.barra_pesquisa.setObjectName("barra_pesquisa")
        self.area_pesuisa.addWidget(self.barra_pesquisa)
        self.botao_pesquisa = QtWidgets.QPushButton(self.central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botao_pesquisa.sizePolicy().hasHeightForWidth())
        self.botao_pesquisa.setSizePolicy(sizePolicy)
        self.botao_pesquisa.setMinimumSize(QtCore.QSize(0, 30))
        self.botao_pesquisa.setStyleSheet("background-color: gray;")
        self.botao_pesquisa.setObjectName("botao_pesquisa")
        self.area_pesuisa.addWidget(self.botao_pesquisa)
        self.verticalLayout_2.addLayout(self.area_pesuisa)
        self.scrollArea = QtWidgets.QScrollArea(self.central)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.area_animes = QtWidgets.QWidget()
        self.area_animes.setGeometry(QtCore.QRect(0, 0, 583, 311))
        self.area_animes.setStyleSheet("background-color: #292326;")
        self.area_animes.setObjectName("area_animes")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.area_animes)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.area_animes_r = QtWidgets.QVBoxLayout()
        self.area_animes_r.setObjectName("area_animes_r")
        self.verticalLayout_4.addLayout(self.area_animes_r)
        self.scrollArea.setWidget(self.area_animes)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.progressBar = QtWidgets.QProgressBar(self.central)
        self.progressBar.setStyleSheet("background-color: white;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.area_resultados = QtWidgets.QHBoxLayout()
        self.area_resultados.setContentsMargins(-1, -1, 0, -1)
        self.area_resultados.setObjectName("area_resultados")
        self.baixar_btn = QtWidgets.QPushButton(self.central)
        self.baixar_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baixar_btn.sizePolicy().hasHeightForWidth())
        self.baixar_btn.setSizePolicy(sizePolicy)
        self.baixar_btn.setMinimumSize(QtCore.QSize(200, 0))
        self.baixar_btn.setStyleSheet("background-color: gray;")
        self.baixar_btn.setObjectName("baixar_btn")
        self.area_resultados.addWidget(self.baixar_btn)
        self.verticalLayout_2.addLayout(self.area_resultados)
        MainWindow.setCentralWidget(self.central)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "DownAnime", None, -1))
        self.botao_pesquisa.setText(QtWidgets.QApplication.translate("MainWindow", "Pesquisar", None, -1))
        self.baixar_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Baixar", None, -1))
        self.actionSobre.setText(QtWidgets.QApplication.translate("MainWindow", "Sobre", None, -1))

